%% FILE NAME: me3020_lab1

%% CLASS: FALL ME 3020

%% DATE: Sept. 13, 2022


%% PURPOSE: 
%  To measure the response of an under-damped
%  second order mechanical system and compare that
%  response to an analytical model         

%% ASSUMPTIONS: 

clc,clear
%% DATA CLEANUP & VARIABLES:
lab_experemental_data = readmatrix('lab1_elvis_data.txt'); 
%imports the ENTIRE datafile as a matrix. 

exp_voltage = lab_experemental_data(90245:110149,2); 
%pulls the second column (voltages) from data off the lab data and chops
%off a lot of useless data points from before and after measurement.
%this also shifts graph around^^^

voltages = exp_voltage+2.33596; 
%moves the steady (ending) state values to the x-axis

times = (1:1:length(voltages))'/10000;
%Matrix of times thats as long as voltage matrix. Increments from
%1 to 26,000 in increments of 1 then div by 10,000 to change to seconds



%% X-AXIS CROSSINGS:
idx = 1; %index for while loop
idy = 1;%index for sizing of pairs so it dont use idx = 10,000

%Loop gets pairs of times and their voltages sloping up
while idx < length(voltages)
    
    if voltages(idx) < 0 && voltages(idx+1) > 0
        
        time_pairs(idy,1) = times(idx);%takes the time associated with
        %the 0> voltage and hands it to col(1). the idy has it placed in
        %front of last # insted of at idx=10,203
        time_pairs(idy,2) = times(idx+1);%voltage>0 next to its lower part.       
        volt_pairs(idy,1) = voltages(idx); %gets voltage pairs
        volt_pairs(idy,2) = voltages(idx+1);       
        idy = idy + 1;%if it gets a hit, moves up index for x-pairs
    end
    idx = idx+1;
end

%Loop gets pairs of times and their voltages sloping down
idx = 1; %resets index, dont reset idy to just keep adding values to pairs
while idx < length(voltages)
    
    if voltages(idx) > 0 && voltages(idx+1) < 0
        
        time_pairs(idy,1) = times(idx);%takes the time associated with
        %the 0> voltage and hands it to col(1). the idy has it placed in
        %front of last # insted of at idx=10,203
        time_pairs(idy,2) = times(idx+1);%same as col(1) but puts the #
        %thats voltage>0 next to its lower part.
        volt_pairs(idy,1) = voltages(idx); %gets voltage pairs
        volt_pairs(idy,2) = voltages(idx+1);
        
        idy = idy + 1;%if it gets a hit, moves up index for x-pairs
    end
    idx = idx+1;
end

%Interpolates for x-intercepts
for x = 1:length(time_pairs)
    frac(x) = -volt_pairs(x,1)/(volt_pairs(x,2)-volt_pairs(x,1));
    subtraction(x) = time_pairs(x,2)-time_pairs(x,1);
    x_int_time(x) = frac(x)*subtraction(x)+time_pairs(x,1);

end

volt_xcross = int16(x_int_time*10000);%takes the x intercept time and turns
%it into whole integer index for voltage.

%% MIN-MAX:

pks = islocalmax(voltages,'MinSeparation',1500); %gets peaks 


vlys = islocalmin(voltages,'MinSeparation',1000); %gets valleys 
%these find a min/max when they get a hit they place a true (1)
%in the spot that voltage was found


%% PLOTS:



%%%%%%%%%%%%%%
for n = 2:length(volt_xcross)
    diff(n) = volt_xcross(n) - volt_xcross(n-1);
    
    
end
diff1 = diff(:,2:9);
period = mean(diff1,'all');
frequency = 1/(period/10000);%frequency

maxes1(:,1) = times(pks); 
maxes2(:,1) = voltages(pks);


for n = 1:length(times)
    V(n) = (-1.711)*exp(-1.15*times(n))*cos(32.85*times(n));%period is rads
end




plot(times,voltages)%plots voltages against time
ylabel('Voltage (V)')
xlabel('Time (s)')
title('Voltage Generated by Torsion-Mass System')
hold on
plot(x_int_time(1:15),voltages(volt_xcross(1:15)),'bo')%plots x-intercepts
plot(times(pks),voltages(pks),'r*',times(vlys),voltages(vlys),'r*')
plot(times,V,'r')
%plots maximums
legend('Exp Voltage','x-intercept','local max/max','','theo values')